In [1]:
import numpy as np
import pandas as pd
from pandas_profiling import profile_report
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\Aman\Downloads\wineQT.csv")
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [4]:
X=df.drop(columns='quality')
y=df['quality']

In [5]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1138    6
1139    6
1140    5
1141    6
1142    5
Name: quality, Length: 1143, dtype: int64

In [6]:
X_train, X_test, y_train, y_test =train_test_split(X,y,random_state=100)

In [7]:
knn = KNeighborsClassifier()

In [8]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
knn.score(X_test,y_test)

0.5104895104895105

In [11]:
para={
    "n_neighbors":[10,20,30,50,70,90,100,150,200,250],
    "weights":['uniform', 'distance'],
    "algorithm":['auto', 'ball_tree', 'kd_tree', 'brute'],
    "leaf_size":[35,40,45,50,55,60],
    "p":[1,2]
}

In [12]:
grid_search_knn=GridSearchCV(estimator=knn, param_grid=para,cv=10, n_jobs=4)

In [13]:
grid_search_knn.fit(X_train,y_train)

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  warnings.warn(


GridSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=4,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [35, 40, 45, 50, 55, 60],
                         'n_neighbors': [10, 20, 30, 50, 70, 90, 100, 150, 200,
                                         250],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [14]:
grid_search_knn.best_params_

{'algorithm': 'auto',
 'leaf_size': 35,
 'n_neighbors': 90,
 'p': 1,
 'weights': 'distance'}

In [10]:
knn2=KNeighborsClassifier(algorithm="auto",n_neighbors=245,weights="distance", leaf_size=35, p=1)

In [11]:
knn2.fit(X_train,y_train)

KNeighborsClassifier(leaf_size=35, n_neighbors=245, p=1, weights='distance')

In [12]:
knn2.score(X_train,y_train)

1.0

In [13]:
knn2.score(X_test,y_test)

0.6223776223776224

In [14]:
import pickle

In [15]:
pickle.dump(knn2, open("knn.pkl","wb"))

In [16]:
# Knn is a lazy learner algo it stores the data not the equation so its file size can vary
# It stores the data from the dataset

In [17]:
pickle.dump(knn, open("knn2.pkl","wb"))

In [18]:
ls

 Volume in drive C is OS
 Volume Serial Number is 5283-A9D9

 Directory of C:\Users\Aman\Data science course\Machine Learning

04-10-2022  13:45    <DIR>          .
04-10-2022  13:45    <DIR>          ..
04-10-2022  11:55    <DIR>          .ipynb_checkpoints
02-09-2022  17:31               540 admission_lr_model.pickle
02-10-2022  13:23         3,676,549 ai4i2020.ipynb
23-08-2022  19:45           288,827 All the types of transformations.ipynb
11-09-2022  21:05         2,141,403 Classification_task.csv
09-09-2022  18:13    <DIR>          CSV
03-10-2022  12:16         1,420,585 Decision Tree and Bagging.ipynb
01-09-2022  14:58         1,040,484 df.html
04-10-2022  13:45            65,377 KNN SVM SVC Stacking.ipynb
05-10-2022  10:00           100,952 knn.pkl
05-10-2022  10:00           100,949 knn2.pkl
20-09-2022  18:28         3,728,675 Linear Regression.ipynb
01-09-2022  14:58               535 linear_reg.sav
03-10-2022  23:32           568,782 Logistic Regression task.ipynb
22-09-2022 

In [19]:
# SVC= support vector classifier

In [30]:
from sklearn.svm import SVC

In [31]:
svc=SVC()

In [32]:
svc.fit(X_train,y_train)

SVC()

In [33]:
svc.score(X_test,y_test)

0.493006993006993

In [ ]:
# Precomputed :- We can derive our own mathematical function

In [36]:
param={
    "kernel" : ['linear', 'poly', 'rbf', 'sigmoid'],
    "C":[.1,.2,.4,.6,1,2,3,10,30,50,100,200,300]
}

In [37]:
svm_grid=GridSearchCV(svc,param_grid=param)

In [38]:
svm_grid.fit(X_train,y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [39]:
svm_grid.best_params_

{'kernel': 'linear'}

In [40]:
sv2=SVC(kernel="linear")

In [41]:
sv2.fit(X_train,y_train)

SVC(kernel='linear')

In [42]:
sv2.score(X_test,y_test)

0.5979020979020979

In [43]:
# SVR :- Support Vector classifier

In [45]:
df=pd.read_csv(r"C:\Users\Aman\Downloads\Admission_Prediction.csv")

In [46]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [54]:
df.dropna(inplace=True)

In [55]:
X=df.drop(columns=["Serial No.","Chance of Admit"])

In [56]:
y=df["Chance of Admit"]

In [57]:
X_train, X_test, y_train, y_test=train_test_split(X,y, random_state=30,test_size=.20)

In [58]:
from sklearn.svm import SVR

In [59]:
svr=SVR()

In [60]:
svr.fit(X_train,y_train)

SVR()

In [65]:
pred=svr.predict(X_test)

In [62]:
from sklearn.metrics import r2_score

In [66]:
r2_score(pred,y_test)

0.25688451806641543

In [69]:
svr.predict([X.iloc[0]])

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([0.87726177])

## Stacking

In [115]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
%matplotlib inline

In [71]:
data=pd.read_csv(r"C:\Users\Aman\Downloads\wineQT.csv")

In [74]:
X=data.drop(columns="quality")

In [75]:
y=data.quality

In [93]:
y.shape

(1143,)

In [94]:
X.shape

(1143, 12)

In [98]:
train, val_train, test, val_test=train_test_split(X,y,test_size=.50,random_state=100)

In [99]:
X_train, X_test, y_train, y_test = train_test_split(train, test,test_size=.25, random_state=100)

In [100]:
knn=KNeighborsClassifier()

In [101]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [102]:
knn.score(X_test,y_test)

0.3776223776223776

In [103]:
svc=SVC()

In [104]:
svc.fit(X_train,y_train)

SVC()

In [105]:
svc.score(X_test,y_test)

0.5034965034965035

In [ ]:
knn.predict(X_test)

In [108]:
pred_knn=knn.predict(val_train)
pred_svc=svc.predict(val_train)

In [109]:
pred_knn

array([5, 5, 6, 5, 6, 5, 6, 4, 6, 6, 6, 5, 6, 7, 6, 6, 5, 7, 6, 7, 6, 5,
       6, 5, 6, 5, 5, 5, 6, 6, 6, 7, 5, 5, 5, 6, 5, 6, 5, 7, 5, 6, 6, 5,
       5, 6, 6, 6, 6, 6, 7, 5, 7, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5,
       5, 5, 6, 5, 6, 6, 4, 6, 5, 5, 4, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 7, 5, 6, 6,
       5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 6, 5, 7, 6, 5, 5,
       6, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 5, 7, 5, 7, 6, 6, 6, 6, 3, 5, 5,
       6, 5, 5, 6, 5, 5, 5, 7, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6,
       7, 5, 5, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6,
       7, 5, 7, 5, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       6, 6, 5, 4, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5,
       7, 5, 5, 6, 6, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6,
       5, 6, 5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 7, 5,
       5, 5, 6, 7, 5, 6, 5, 5, 5, 4, 6, 6, 6, 5, 5,

In [110]:
pred_svc

array([5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 6, 6, 5, 5,
       5, 6, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6,
       6, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6,
       6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6,
       5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 5,
       6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5,
       6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5,
       5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5,
       6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6,
       5, 5, 6, 6, 6, 6, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 6,
       5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6,

In [113]:
input3=np.column_stack((pred_knn,pred_svc))

In [114]:
pd.DataFrame(input3)

0  1
0    5  5
1    5  5
2    6  6
3    5  6
4    6  6
..  .. ..
567  6  6
568  6  6
569  6  6
570  6  5
571  6  5

[572 rows x 2 columns]

In [117]:
output=val_test

In [118]:
rf=RandomForestClassifier()

In [119]:
rf.fit(input3,output)

RandomForestClassifier()

In [122]:
# knn
# svc
# rf

In [127]:
knn_output=knn.predict(X_test)
svc_output=svc.predict(X_test)

In [129]:
out_stack=np.column_stack((knn_output,svc_output))

In [130]:
rf.predict(out_stack)

array([5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5,
       6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5,
       5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5,
       5, 6, 5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 5, 6,
       5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6,
       5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5,
       6, 5, 5, 5, 7, 6, 5, 5, 5, 5, 5], dtype=int64)

In [132]:
rf.score(out_stack,y_test)

0.38461538461538464

# Task
link:-
https://archive.ics.uci.edu/ml/datasets/Activity+recognition+with+healthy+older+people+using+a+batteryless+wearable+sensor
1. Logistic Regression, SVC, KNN, DT, Stacking and Bagging
2. Give detailed Description and explanation of each and every model that you are going to use
3. Then build the model then build a physical file of the model
4. Then Deploy