#### Q When to apply Linear Regression????
Ans: Points to be checked before applying Linear Regression
1. There shoud be a relationship between y (dependent/label) and X (Independent/Features) variables.
2. Mean of residual(predicted value) should be zero.
3. Error terms (i.e c) are not suppose to be correalted.
4. X and residual are suppose to be uncorrelated (# Exogenity).
5. Error terms must show constant variance (#Homoscedascity).
6. There should not be any Multicollinearity (Relationship between features and features).
7. Error terms are suppose to be Normally Distributed

In [1]:
import numpy as np
import pandas as pd
import pickle 
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport

In [2]:
df=pd.read_csv(r'C:/Users/Aman/Downloads/advertising.csv')
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

#### Problem Statement :-
Client has told you to build a model if he is investing x amount of money inTV	Radio	Newspaper so what would be the sales able to do. 
 1. Which mode of advertisment would be effective ?
 2. If the relationship is possible then derive it!

In [48]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [49]:
pf=ProfileReport(df)

In [50]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [51]:
pf.to_file('df.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [52]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [53]:
# Sales = m TV + c
#  y = m x + c
# m is slope/coefficient
# c is intercept
# Objective is to find minimum error

In [54]:
# Selecting a feature 
# X is independent feature
X=df[['TV']]
X

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [55]:
# Selecting a lable
# y is dependent feature
y=df.Sales
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [56]:
# For linear regression
from sklearn.linear_model import LinearRegression

In [57]:
# Making an object LinearRegression
lin_reg=LinearRegression() 

In [58]:
lin_reg.fit(X,y)

LinearRegression()

In [59]:
# Sales = m TV + c
#  y = m x + c
# m is slope/coefficient
# c is intercept/error
# Objective is to find minimum error

In [60]:
# Our c value is intercept
lin_reg.intercept_

6.974821488229891

In [61]:
# m is our coefficient
lin_reg.coef_

array([0.05546477])

In [62]:
# .sav is for bytecode format
file="linear_reg.sav"
pickle.dump(lin_reg,open(file,'wb')) #wb write binary


In [63]:
lin_reg.predict([[45]])

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [64]:
l=[4,5,6,7,89,34,45,67,23]

In [65]:
for i in l:
    print(lin_reg.predict([[i]]))

[7.19668057]
[7.25214534]
[7.30761011]
[7.36307488]
[11.91118606]
[8.86062368]
[9.47073616]
[10.69096111]
[8.25051121]


C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have val

In [66]:
save_model=pickle.load(open(file,'rb'))

In [67]:
save_model.predict([[45]])

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [68]:
lin_reg.score(X,y)

0.8121757029987414

In [69]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [74]:
# Independent features 
X=df.iloc[:,:3]
X

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [75]:
# Dependent Features
y=df.iloc[:,3:]
y

Sales
0     22.1
1     10.4
2     12.0
3     16.5
4     17.9
..     ...
195    7.6
196   14.0
197   14.8
198   25.5
199   18.4

[200 rows x 1 columns]

In [76]:
linear_reg=LinearRegression()

In [77]:
linear_reg.fit(X,y)

LinearRegression()

In [78]:
linear_reg.intercept_

array([4.62512408])

In [79]:
linear_reg.coef_

array([[0.05444578, 0.10700123, 0.00033566]])

In [88]:
linear_reg.score(X,y)

In [ ]:
# Another way to build model
# It will give only statical analysis of a model

In [13]:
def ordinary_least_square(x,y):
    import statsmodels.api as sm
    x=sm.add_constant(x)
    model=sm.OLS(y,x).fit()
    print(model.summary())

In [14]:
X=df.drop(columns="Sales")
y=df["Sales"]

In [15]:
ordinary_least_square(X,y)

                            OLS Regression Results                            
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Fri, 21 Oct 2022   Prob (F-statistic):           8.13e-99
Time:                        11:56:08   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.6251      0.308     15.041      0.0

In [85]:
import statsmodels.formula.api as smfa #ols :- Ordinary least square model
lm=smfa.ols(formula='Sales ~ TV',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.811
Method:                 Least Squares   F-statistic:                     856.2
Date:                Thu, 01 Sep 2022   Prob (F-statistic):           7.93e-74
Time:                        15:21:37   Log-Likelihood:                -448.99
No. Observations:                 200   AIC:                             902.0
Df Residuals:                     198   BIC:                             908.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.9748      0.323     21.624      0.000       6.339       7.611
TV             0.0555      0.002     29.260      0.000       0.052       0.059
==============================================================================
Omnibus:                        0.013   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.993   Jarque-Bera (JB):                0.043
Skew:                          -0.018   Prob(JB):                        0.979
Kurtosis:                       2.938   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [87]:
lm=smfa.ols(formula='Sales ~ TV + Radio + Newspaper',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Thu, 01 Sep 2022   Prob (F-statistic):           8.13e-99
Time:                        15:23:34   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6251      0.308     15.041      0.000       4.019       5.232
TV             0.0544      0.001     39.592      0.000       0.052       0.057
Radio          0.1070      0.008     12.604      0.000       0.090       0.124
Newspaper      0.0003      0.006      0.058      0.954      -0.011       0.012
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   2.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.655
Skew:                          -0.431   Prob(JB):                     9.88e-07
Kurtosis:                       4.605   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### Addmission Prediction

In [1]:
# Importing the librarys
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, ElasticNet, RidgeCV, LassoCV, ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

##### This dataset is open sourse

##### Requirement:-
Build a model to predict the chance of admission after giving some parameter to the model.

In [2]:
# Loading the dataset Admission_Prediction.csv
df=pd.read_csv(r"C:\Users\Aman\Downloads\Admission_Prediction.csv")
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [3]:
from pandas_profiling import ProfileReport

In [4]:
pf=ProfileReport(df)
pf.to_widgets()

Summarize dataset:   0%|          | 0/22 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
df.dtypes 

Serial No.             int64
GRE Score            float64
TOEFL Score          float64
University Rating    float64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [6]:
# Filling the missing values with Average

In [7]:
df['GRE Score']=df['GRE Score'].fillna(df['GRE Score'].mean())

In [8]:
df

Serial No.   GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1  337.000000        118.0                4.0  4.5  4.5  9.65   
1             2  324.000000        107.0                4.0  4.0  4.5  8.87   
2             3  316.558763        104.0                3.0  3.0  3.5  8.00   
3             4  322.000000        110.0                3.0  3.5  2.5  8.67   
4             5  314.000000        103.0                2.0  2.0  3.0  8.21   
..          ...         ...          ...                ...  ...  ...   ...   
495         496  332.000000        108.0                5.0  4.5  4.0  9.02   
496         497  337.000000        117.0                5.0  5.0  5.0  9.87   
497         498  330.000000        120.0                5.0  4.5  5.0  9.56   
498         499  312.000000        103.0                4.0  4.0  5.0  8.43   
499         500  327.000000        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [9]:
df['TOEFL Score']=df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [10]:
df['University Rating']=df['University Rating'].fillna(df['University Rating'].mean())

In [11]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.121649    3.374000   
std    144.481833   11.103952     6.051338           1.128802    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  309.000000   103.000000           2.000000    2.500000   
50%    250.500000  316.558763   107.000000           3.000000    3.500000   
75%    375.250000  324.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [12]:
# Checking if null values are present
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [13]:
# Droppping the serial column
df.drop(columns='Serial No.',inplace=True)

In [14]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [15]:
# Target variable (dependent feature)
y=df['Chance of Admit']
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [16]:
# Feature columns are
x=df.drop(columns=['Chance of Admit'])
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

What is Standardization???

Standardization helps us to reduce the data into standard normal distribution where mean=0,
Standard Deviation=1 (It help is to bring the data/Features into same scale)

In [17]:
scalar=StandardScaler()

In [20]:
arr=scalar.fit_transform(x)
arr

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [21]:
df1=pd.DataFrame(arr)
df1

0         1         2         3         4         5         6
0    1.842741e+00  1.788542  0.778906  1.137360  1.098944  1.776806  0.886405
1    6.708143e-01 -0.031058  0.778906  0.632315  1.098944  0.485859  0.886405
2    5.124333e-15 -0.527313 -0.107877 -0.377773  0.017306 -0.954043  0.886405
3    4.905178e-01  0.465197 -0.107877  0.127271 -1.064332  0.154847  0.886405
4   -2.306679e-01 -0.692731 -0.994659 -1.387862 -0.523513 -0.606480 -1.128152
..            ...       ...       ...       ...       ...       ...       ...
495  1.392000e+00  0.134360  1.665688  1.137360  0.558125  0.734118  0.886405
496  1.842741e+00  1.623124  1.665688  1.642404  1.639763  2.140919  0.886405
497  1.211704e+00  2.119379  1.665688  1.137360  1.639763  1.627851  0.886405
498 -4.109644e-01 -0.692731  0.778906  0.632315  1.639763 -0.242367 -1.128152
499  9.412590e-01  0.961451  0.778906  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

In [22]:
df1.profile_report()

Summarize dataset:   0%|          | 0/20 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [23]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   4.350520e-15  9.419132e-16  5.608847e-16  2.926548e-16 -1.332268e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.394225e+00 -2.512331e+00 -1.881441e+00 -2.397950e+00 -2.686789e+00   
25%   -6.814090e-01 -6.927310e-01 -9.946589e-01 -8.828175e-01 -5.235128e-01   
50%    5.124333e-15 -3.105811e-02 -1.078766e-01  1.272712e-01  1.730621e-02   
75%    6.708143e-01  7.960330e-01  7.789057e-01  6.323155e-01  5.581253e-01   
max    2.113186e+00  2.119379e+00  1.665688e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.091971e-15 -2.202682e-16  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

In [25]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_df=pd.DataFrame(columns=['Features'],data=x.columns)

In [26]:
s=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [27]:
vif_df['vif']=s

In [28]:
vif_df

Features       vif
0          GRE Score  4.153268
1        TOEFL Score  3.792866
2  University Rating  2.508768
3                SOP  2.775750
4                LOR  2.037308
5               CGPA  4.651670
6           Research  1.459311

In [29]:
# df_vif.append(df_vif['vif'])

In [30]:
# df_vif['vif']=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [31]:
# df_vif['Features']=X.columns

In [32]:
arr

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [46]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [158]:
x_train, x_test, y_train, y_test = train_test_split(arr,y,train_size=0.85,random_state=90)

In [159]:
x_train

array([[ 5.12433309e-15, -1.96476326e-01,  7.78905651e-01, ...,
        -5.23512832e-01, -1.76164592e-01, -1.12815215e+00],
       [ 1.39200006e+00,  1.34360100e-01,  1.66568791e+00, ...,
         5.58125251e-01,  7.34118435e-01,  8.86405260e-01],
       [ 1.12155539e+00,  9.61451165e-01,  1.66568791e+00, ...,
         1.09894429e+00,  1.44579426e+00,  8.86405260e-01],
       ...,
       [-5.01112585e-01, -3.61894539e-01, -1.07876604e-01, ...,
        -5.23512832e-01, -2.09265793e-01,  8.86405260e-01],
       [-6.81409027e-01, -5.27312752e-01, -9.94658860e-01, ...,
        -1.06433187e+00, -5.23727202e-01, -1.12815215e+00],
       [-1.58289124e+00, -2.18149488e+00, -1.88144112e+00, ...,
        -2.68678900e+00, -2.04638245e+00, -1.12815215e+00]])

In [160]:
lr=LinearRegression()

In [161]:
lr.fit(x_train,y_train)

LinearRegression()

In [162]:
import pickle
pickle.dump(lr, open('admission_lr_model.pickle', 'wb'))

In [163]:
lr.predict(test1)

array([0.80570555])

In [164]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [165]:
test1=scalar.transform([[324.000000,107.0,4.0,4.0,4.5,8.87,1]])
test1

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.67081429, -0.03105811,  0.77890565,  0.63231549,  1.09894429,
         0.48585943,  0.88640526]])

In [166]:
test2=scalar.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])
test2

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

In [167]:
model1=pickle.load(open('admission_lr_model.pickle','rb'))

In [168]:
model1.predict(test2)

array([0.95108404])

In [169]:
lr.score(x_test,y_test)

0.8810184171399501

In [170]:
# Creating a function for adjusted R-square
def adjusted_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adj_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adj_r2

In [171]:
adjusted_r2(x_test,y_test)

0.8685875054978554

In [172]:
lr.coef_

array([0.02036765, 0.01536669, 0.00708784, 0.0019331 , 0.01728481,
       0.07170826, 0.01244546])

In [173]:
lr.intercept_

0.7209099030741182

### Regularization
In regularization we control the value of m and c to get more generalized results

1. LASSO (L1) (Least Absolute Shrinkage and Selection Output) 

In [207]:
lassocv=LassoCV(alphas=None,cv=50,max_iter=100000,normalize=True)
lassocv.fit(x_train,y_train)

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(


LassoCV(cv=50, max_iter=100000, normalize=True)

In [208]:
lassocv.alpha_

5.98321957796534e-06

In [209]:
lasso=Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=5.98321957796534e-06)

In [210]:
lasso.score(x_test,y_test)

0.881021201215447

In [224]:
ridgecv=RidgeCV(alphas=np.random.uniform(0,10,50),cv=10,normalize=True)

In [225]:
ridgecv.fit(x_train,y_train)

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn

C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Aman\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn

RidgeCV(alphas=array([6.13389994, 1.67295397, 9.38876342, 7.28233058, 3.21335269,
       3.43551961, 7.10711969, 3.16988757, 7.92259317, 6.76086824,
       2.59887802, 3.47606633, 9.69880097, 3.44239654, 1.48763097,
       0.76310565, 3.02998178, 8.01459952, 4.04166633, 3.53981389,
       2.75499166, 9.69949269, 5.0190277 , 6.65718607, 7.85878486,
       6.47166102, 4.00261605, 6.22531333, 3.69782966, 6.18360698,
       4.12443408, 8.28441902, 5.86270476, 8.63322888, 3.98663301,
       3.67145186, 3.31473429, 7.71711229, 0.57740851, 8.91408561,
       0.90186575, 8.05447754, 8.92856755, 7.8600778 , 3.79382087,
       3.8215287 , 1.28329105, 8.47670089, 6.79066375, 6.506033  ]),
        cv=10, normalize=True)

In [226]:
ridgecv.alpha_

0.5774085124503614

In [222]:
np.random.uniform(0,10,50)

array([5.00581707, 7.92076279, 8.43093399, 0.85050063, 1.62276113,
       7.38783714, 3.15702193, 2.0268556 , 1.06560795, 9.88197995,
       7.03862604, 8.00817103, 1.09120476, 9.85689818, 5.48717926,
       6.36496608, 2.85600424, 2.75103229, 9.65309555, 0.08741691,
       7.12842172, 9.76380804, 0.16064162, 4.3954795 , 3.9435331 ,
       3.49348384, 2.38423069, 8.04480281, 3.3583329 , 3.04051862,
       2.74401305, 7.37591557, 5.5958316 , 9.57735961, 3.9987805 ,
       6.14025879, 1.80536108, 2.17186364, 6.25709276, 1.47221999,
       6.60702422, 4.64412806, 2.11379402, 7.55378784, 1.31991867,
       6.68697349, 6.14111184, 2.09271536, 2.88520274, 7.36142058])

In [227]:
ridge_lr=Ridge(alpha=ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=0.5774085124503614)

In [228]:
ridge_lr.score(x_test,y_test)

0.8809502867098982

In [230]:
elastic=ElasticNetCV(alphas=None,cv=10)
elastic.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [231]:
elastic.alpha_

0.0006983568345560056

In [232]:
elastic.l1_ratio

0.5

In [234]:
elastic_lr=ElasticNet(alpha=elastic.alpha_,l1_ratio=elastic.l1_ratio)

In [235]:
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.0006983568345560056)

In [236]:
elastic_lr.score(x_test,y_test)

0.8811439600269575

Task

In [ ]:
# Problem statement 
You have to build a model where you have to check if dataset is going to fail (value=1) 
at which column [Machine failure, TWF, HDF, PWF, OSF, RNF]

Figure out x column!
# label
y is Air Temperature


In [ ]:
Setps to follow
1. load the data
2. Profiling the data
3. Write your analysis/Observation pf data
4. If there is some nan go for imputation
5. If data set is not normal then handel it
6. check multicollinearity
7. Build the model(Linear Regression)
8. Save it
9. Model accuracy
10. ten test case 

In [91]:
import numpy as np
import pandas as pd
import pickle 
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport

In [92]:
df=pd.read_csv(r'C:/Users/Aman/Downloads/ai4i2020.csv')
df

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6   
1         2     L47181    L                298.2                    308.7   
2         3     L47182    L                298.1                    308.5   
3         4     L47183    L                298.2                    308.6   
4         5     L47184    L                298.2                    308.7   
...     ...        ...  ...                  ...                      ...   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                       1551         42.8                0                0   
1                       1408         46.3                3                0   
2                       1498         49.4                5                0   
3                       1433         39.5                7                0   
4                       1408         40.0                9                0   
...                      ...          ...              ...              ...   
9995                    1604         29.5               14                0   
9996                    1632         31.8               17                0   
9997                    1645         33.4               22                0   
9998                    1408         48.5               25                0   
9999                    1500         40.2               30                0   

      TWF  HDF  PWF  OSF  RNF  
0       0    0    0    0    0  
1       0    0    0    0    0  
2       0    0    0    0    0  
3       0    0    0    0    0  
4       0    0    0    0    0  
...   ...  ...  ...  ...  ...  
9995    0    0    0    0    0  
9996    0    0    0    0    0  
9997    0    0    0    0    0  
9998    0    0    0    0    0  
9999    0    0    0    0    0  

[10000 rows x 14 columns]

In [93]:
pf=ProfileReport(df)

In [94]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/27 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [95]:
# My Observations
# 1. There are no missing values
# 2. Air Temperature is correlated to process temperaure 

In [96]:
df=df[['Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF']].copy()

In [97]:
df

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                   298.1                    308.6                    1551   
1                   298.2                    308.7                    1408   
2                   298.1                    308.5                    1498   
3                   298.2                    308.6                    1433   
4                   298.2                    308.7                    1408   
...                   ...                      ...                     ...   
9995                298.8                    308.4                    1604   
9996                298.9                    308.4                    1632   
9997                299.0                    308.6                    1645   
9998                299.0                    308.7                    1408   
9999                299.0                    308.7                    1500   

      Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0            42.8                0                0    0    0    0    0    0  
1            46.3                3                0    0    0    0    0    0  
2            49.4                5                0    0    0    0    0    0  
3            39.5                7                0    0    0    0    0    0  
4            40.0                9                0    0    0    0    0    0  
...           ...              ...              ...  ...  ...  ...  ...  ...  
9995         29.5               14                0    0    0    0    0    0  
9996         31.8               17                0    0    0    0    0    0  
9997         33.4               22                0    0    0    0    0    0  
9998         48.5               25                0    0    0    0    0    0  
9999         40.2               30                0    0    0    0    0    0  

[10000 rows x 11 columns]

In [98]:
y=df.iloc[:,0]
y

0       298.1
1       298.2
2       298.1
3       298.2
4       298.2
        ...  
9995    298.8
9996    298.9
9997    299.0
9998    299.0
9999    299.0
Name: Air temperature [K], Length: 10000, dtype: float64

In [99]:
X=df.iloc[:,1:]
X.columns

Index(['Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.33, random_state=1)

In [101]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()

In [102]:
X_train

Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
2961                    309.4                    1654         32.8   
2919                    309.6                    1726         30.0   
2136                    308.9                    1588         41.5   
4283                    309.9                    1334         61.0   
9820                    309.5                    1568         36.7   
...                       ...                     ...          ...   
2895                    309.6                    1473         48.1   
7813                    311.5                    1455         41.7   
905                     306.1                    1474         41.2   
5192                    313.1                    1310         62.9   
235                     308.3                    1680         33.7   

      Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
2961               57                0    0    0    0    0    0  
2919              147                0    0    0    0    0    0  
2136              150                0    0    0    0    0    0  
4283              182                1    0    1    0    0    0  
9820              182                0    0    0    0    0    0  
...               ...              ...  ...  ...  ...  ...  ...  
2895               87                0    0    0    0    0    0  
7813              130                0    0    0    0    0    0  
905               156                0    0    0    0    0    0  
5192              130                0    0    0    0    0    0  
235               185                0    0    0    0    0    0  

[6700 rows x 10 columns]

In [103]:
X_test

Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
9953                    307.8                    1565         35.3   
3850                    311.0                    1421         41.3   
4962                    312.7                    1456         51.2   
3886                    311.3                    1392         50.5   
5437                    312.6                    1394         46.4   
...                       ...                     ...          ...   
2195                    308.9                    1613         30.8   
4095                    310.5                    1459         43.2   
543                     309.3                    1563         36.1   
2704                    309.2                    1608         34.4   
1586                    308.4                    1486         44.2   

      Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
9953              119                0    0    0    0    0    0  
3850              182                0    0    0    0    0    0  
4962              160                0    0    0    0    0    0  
3886               51                0    0    0    0    0    0  
5437               82                0    0    0    0    0    0  
...               ...              ...  ...  ...  ...  ...  ...  
2195               80                0    0    0    0    0    0  
4095              148                0    0    0    0    0    0  
543               100                0    0    0    0    0    0  
2704               68                0    0    0    0    0    0  
1586              196                0    0    0    0    0    0  

[3300 rows x 10 columns]

In [104]:
lin_reg.fit(X_train,y_train)

LinearRegression()

In [105]:
# print(lin_reg.intercept_)
# print(lin_reg.coef_)
lin_reg.score(X_test,y_test)

0.7707007957587264

In [108]:
lin_reg.predict(X_test[:100])

array([297.37941698, 301.13826981, 303.16307863, 301.48575987,
       303.01883373, 299.51287693, 298.69313684, 297.53728627,
       297.62448538, 298.07406782, 300.2914907 , 297.98021698,
       300.6859016 , 297.71933317, 301.264544  , 300.90683752,
       302.19078687, 301.97225076, 301.76054243, 300.55664466,
       301.8576735 , 299.27232297, 299.51233831, 298.09596614,
       299.29319653, 298.07516341, 297.47496863, 302.67794145,
       300.18183172, 301.54953328, 297.36058827, 298.00988571,
       302.58970658, 299.77428154, 300.93411105, 299.96232755,
       299.58952913, 298.8918522 , 299.35659612, 297.2465472 ,
       300.53354358, 296.42829139, 299.37507879, 297.59474162,
       299.6294576 , 300.07671841, 301.42615189, 298.43590384,
       300.21270565, 300.32475035, 301.26134709, 299.83282401,
       298.76189287, 297.10275506, 301.43203955, 301.98004387,
       299.83398592, 300.34544283, 297.48665019, 302.3519808 ,
       297.97039485, 303.86376074, 302.20794021, 299.15

In [17]:
x=df[['Process temperature [K]']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[-66.14315172]
[[1.18110166]]


0.7675637525032573

In [20]:
x=df[['Rotational speed [rpm]']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[299.61572345]
[[0.00025293]]


0.0005139497020001382

In [21]:
x=df[['Torque [Nm]']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[300.11547419]
[[-0.00276451]]


0.0001898284080226187

In [22]:
x=df[['Tool wear [min]']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[299.95793793]
[[0.00043531]]


0.00019190083426545712

In [23]:
x=df[['Machine failure']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[299.97399855]
[[0.91243213]]


0.006815441915586584

In [24]:
df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')

In [25]:
x=df[['TWF']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[300.00357645]
[[0.29424964]]


9.909652775552669e-05

In [26]:
x=df[['HDF']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[299.97519474]
[[2.58567483]]


0.018997367811685706

In [27]:
x=df[['PWF']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[300.00425038]
[[0.0715391]]


1.2037493701377855e-05

In [28]:
x=df[['OSF']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[300.00453444]
[[0.04036352]]


3.951829537718332e-06

In [29]:
x=df[['RNF']]
y=df[['Air temperature [K]']]
lin_reg.fit(x,y)
print(lin_reg.intercept_)
print(lin_reg.coef_)
lin_reg.score(x,y)

[300.00338643]
[[0.81240304]]


0.0003128540912330502

In [2]:
def ecludien_distance(X1,Y1,X2,Y2):
    import math
    result=(X1-X2)**2+(Y1-Y2)**2
    print(math.sqrt(result))

In [12]:
ecludien_distance(2,11,2,8)

3.0
